% Online Lemma Segmentation Chapter with LaTeX code only

%----------------------------------------------------------------------------------------
<<global_opts_online, echo=FALSE, cache=FALSE, include=FALSE>>=
library(knitr)
library(here)

knitr::opts_chunk$set(
  echo = FALSE
)
here::here()
set_parent(here('Asberry_Dissertation/Dissertation.Rnw'))
@
%----------------------------------------------------------------------------------------

%----------------------------------------------------------------------------------------
% Load statistics in memory from separate file
%contentOnlinesegMono, child='Statistics/Monolingual_lemma/target_syl_mono_viz.rnw'), include=FALSE>>=
%@
%----------------------------------------------------------------------------------------

%----------------------------------------------------------------------------------------
% Load statistics in memory from separate file
%contentOnlinesegL2, child='Statistics/L2_lemma/target_syl_l2_viz.rnw'), include=FALSE>>=
%@
%----------------------------------------------------------------------------------------

\chapter{Online Segmentation} % Main chapter title

\label{onlineseg} % for referencing this chapter elsewhere, use \ref{onlineseg}

%----------------------------------------------------------------------------------------
%	SECTION 0
%----------------------------------------------------------------------------------------
% Not needed for introduction
%\section{Abstract}

%----------------------------------------------------------------------------------------
%	SECTION 1
%----------------------------------------------------------------------------------------

\section{Introduction}


%-----------------------------------
%	SECTION 2
%-----------------------------------
\section{Background}



%-----------------------------------
%	SECTION 3
%-----------------------------------

\section{Present Study}



%----------------------------------------------------------------------------------------
%	SECTION 2
%----------------------------------------------------------------------------------------

%\section{Methods}

%Not needed

%-----------------------------------
%	SUBSECTION 2-1
%-----------------------------------
%\subsection{Participants}

%Probably still important here to some degree

%Give accurate descriptions of participant groups, how they were classified, number of participants, etc. 


%----------------------------------------------------------------------------------------
%	SECTION 3
%----------------------------------------------------------------------------------------

%\section{Results}

%Not needed


%----------------------------------------------------------------------------------------
%	SECTION 4
%----------------------------------------------------------------------------------------

%\section{Discussion}
%Not needed


%----------------------------------------------------------------------------------------
%	SECTION 5
%----------------------------------------------------------------------------------------

%\section{References}

%Insert references for this chapter here.
