% Appendix BLP with LaTeX code only

%----------------------------------------------------------------------------------------
%Change ParentTemplate to something unique and meaningful to your project
<<parentBLP, echo=FALSE, cache=FALSE>>=
rm(list=ls())
library(knitr)
set_parent('../Dissertation.rnw')
@
%----------------------------------------------------------------------------------------


\chapter{Basic Language Profile (BLP)} % Main appendix title

\label{Appendix_BLP} % Change Label; for referencing this appendix elsewhere, use \ref{Appendix_BLP}

Write your content here.