% Appendix Template with LaTeX code only

%----------------------------------------------------------------------------------------
%Change ParentTemplate to something unique and meaningful to your project
<<parentFeedback, echo=FALSE, cache=FALSE>>=
rm(list=ls())
library(knitr)
set_parent('../Dissertation.rnw')
@
%----------------------------------------------------------------------------------------


\chapter{Feedback Revisions} % Main appendix title
\label{app-label} % Change Label; for referencing this appendix elsewhere, use \ref{AppendixLabel}

\listoftodos